# Generated by Django 5.0 on 2024-12-19 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='generalinfo',
            table='general_company_info',
        ),
    ]
