# Generated by Django 5.0 on 2024-12-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='icon',
            new_name='bootstrap_icon',
        ),
        migrations.AddField(
            model_name='service',
            name='fontawsome_icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
