# Generated by Django 5.0 on 2024-12-23 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_frequentlyaskedquestions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FrequentlyAskedQuestions',
            new_name='FrequentlyAskedQuestion',
        ),
    ]
