# Generated by Django 5.0 on 2025-01-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0012_alter_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_pic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
